<?php

declare(strict_types=1);

function carceris_report_facility_name(): string
{
    return setting('facility_name', 'Correctional Facility') ?: 'Correctional Facility';
}

function carceris_report_title(array $logDay): string
{
    return carceris_print_log_title();
}

function carceris_report_subject(array $logDay): string
{
    return carceris_report_title($logDay) . ' - ' . format_log_date($logDay['operational_date']);
}

function carceris_report_entry_count_label(array $entries): string
{
    $count = count($entries);

    return $count . ' ' . ($count === 1 ? 'entry' : 'entries');
}

function carceris_render_log_report_plain_text(array $logDay, array $entries): string
{
    $lines = [];

    $lines[] = carceris_report_title($logDay);
    $lines[] = str_repeat('=', strlen(carceris_report_title($logDay)));
    $lines[] = 'Operational Period: ' . $logDay['log_label'];
    $lines[] = 'Operational Date: ' . format_log_date($logDay['operational_date']);
    $lines[] = 'Generated: ' . carceris_format_datetime(new DateTimeImmutable('now'));
    $lines[] = 'Generated By: Carceris';
    $lines[] = 'Entry Count: ' . carceris_report_entry_count_label($entries);
    $lines[] = '';
    $lines[] = 'Entries';
    $lines[] = '-------';

    if (!$entries) {
        $lines[] = 'No log entries were recorded for this operational period.';
        return implode(PHP_EOL, $lines) . PHP_EOL;
    }

    foreach ($entries as $entry) {
        $parts = [
            format_log_time($entry['event_time']),
            $entry['category'] ?? '',
            ucfirst((string) ($entry['priority'] ?? 'normal')),
            'Status: ' . entry_status_label($entry),
        ];

        if (!empty($entry['location'])) {
            $parts[] = 'Location: ' . $entry['location'];
        }

        if (!empty($entry['inmate_name'])) {
            $parts[] = 'Inmate: ' . $entry['inmate_name'];
        }

        if (!empty($entry['created_by_name'])) {
            $parts[] = 'Officer: ' . $entry['created_by_name'];
        }

        $lines[] = implode(' | ', $parts);
        $lines[] = trim((string) ($entry['entry_text'] ?? ''));

        $lateNote = entry_late_note($entry);

        if ($lateNote !== '') {
            $lines[] = $lateNote;
        }

        $statusNote = entry_status_note($entry);

        if ($statusNote !== '') {
            $lines[] = $statusNote;
        }

        $lines[] = '';
    }

    return implode(PHP_EOL, $lines);
}

function carceris_render_log_report_html(array $logDay, array $entries): string
{
    $title = carceris_report_title($logDay);
    $generatedAt = carceris_format_datetime(new DateTimeImmutable('now'));
    $entryCount = carceris_report_entry_count_label($entries);

    ob_start();
    ?>
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title><?= e($title) ?></title>
    <style>
        body {
            color: #111827;
            font-family: Arial, Helvetica, sans-serif;
            font-size: 14px;
            line-height: 1.5;
            margin: 24px;
        }

        .report-header {
            border-bottom: 2px solid #111827;
            margin-bottom: 18px;
            padding-bottom: 14px;
        }

        h1 {
            font-size: 24px;
            margin: 0 0 8px;
        }

        .meta {
            color: #374151;
            margin: 2px 0;
        }

        table {
            border-collapse: collapse;
            width: 100%;
        }

        th,
        td {
            border: 1px solid #d1d5db;
            padding: 8px;
            text-align: left;
            vertical-align: top;
        }

        th {
            background: #f3f4f6;
            font-size: 12px;
            letter-spacing: 0.04em;
            text-transform: uppercase;
        }

        .late-note {
            border-left: 3px solid #92400e;
            color: #92400e;
            font-size: 12px;
            font-weight: 700;
            margin-top: 8px;
            padding-left: 8px;
        }

        .empty {
            color: #6b7280;
            font-style: italic;
        }
    </style>
</head>
<body>
<header class="report-header">
    <h1><?= e($title) ?></h1>
    <p class="meta"><strong>Operational Period:</strong> <?= e($logDay['log_label']) ?></p>
    <p class="meta"><strong>Operational Date:</strong> <?= e(format_log_date($logDay['operational_date'])) ?></p>
    <p class="meta"><strong>Generated:</strong> <?= e($generatedAt) ?></p>
    <p class="meta"><strong>Generated By:</strong> Carceris</p>
    <p class="meta"><strong>Entry Count:</strong> <?= e($entryCount) ?></p>
</header>

<?php if (!$entries): ?>
    <p class="empty">No log entries were recorded for this operational period.</p>
<?php else: ?>
    <table>
        <thead>
            <tr>
                <th>Time</th>
                <th>Category</th>
                <th>Priority</th>
                <th>Location</th>
                <th>Inmate</th>
                <th>Entry</th>
                <th>Status</th>
                <th>Officer</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($entries as $entry): ?>
                <tr>
                    <td><?= e(format_log_time($entry['event_time'])) ?></td>
                    <td><?= e($entry['category']) ?></td>
                    <td><?= e(ucfirst((string) $entry['priority'])) ?></td>
                    <td><?= e($entry['location'] ?? '') ?></td>
                    <td><?= e($entry['inmate_name'] ?? '') ?></td>
                    <td>
                        <?= nl2br(e($entry['entry_text'])) ?>
                        <?php $lateNote = entry_late_note($entry); ?>
                        <?php if ($lateNote !== ''): ?>
                            <div class="late-note"><?= e($lateNote) ?></div>
                        <?php endif; ?>
                        <?php $statusNote = entry_status_note($entry); ?>
                        <?php if ($statusNote !== ''): ?>
                            <div class="late-note"><?= e($statusNote) ?></div>
                        <?php endif; ?>
                    </td>
                    <td><?= e(entry_status_label($entry)) ?></td>
                    <td><?= e($entry['created_by_name'] ?? 'Unknown') ?></td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
<?php endif; ?>
</body>
</html>
    <?php

    return (string) ob_get_clean();
}

function carceris_report_download_filename(array $logDay, string $format): string
{
    $extension = match ($format) {
        'html' => 'html',
        'pdf' => 'pdf',
        default => 'txt',
    };

    return carceris_daily_log_filename_base($logDay) . '.' . $extension;
}

function carceris_record_report_generation(
    array $logDay,
    string $format,
    array $user,
    string $status = 'generated'
): int {
    $bodyFormat = match ($format) {
        'html' => 'html',
        'pdf' => 'none',
        default => 'plain_text',
    };

    $attachmentFormat = $format === 'pdf' ? 'pdf' : 'none';

    $stmt = db()->prepare(
        'INSERT INTO report_downloads
            (log_day_id, body_format, attachment_format, subject, status, triggered_by, created_at)
         VALUES
            (:log_day_id, :body_format, :attachment_format, :subject, :status, :triggered_by, NOW())'
    );

    $stmt->execute([
        'log_day_id' => (int) $logDay['id'],
        'body_format' => $bodyFormat,
        'attachment_format' => $attachmentFormat,
        'subject' => carceris_report_subject($logDay),
        'status' => $status === 'failed' ? 'failed' : 'generated',
        'triggered_by' => (int) $user['id'],
    ]);

    return (int) db()->lastInsertId();
}


function carceris_report_delivery_already_sent(int $logDayId): bool
{
    $stmt = db()->prepare(
        'SELECT COUNT(*)
         FROM report_email_deliveries
         WHERE log_day_id = :log_day_id
           AND delivery_type = "automatic"
           AND status = "sent"'
    );
    $stmt->execute(['log_day_id' => $logDayId]);

    if ((int) $stmt->fetchColumn() > 0) {
        return true;
    }

    if (carceris_schema_table_exists('report_deliveries')) {
        $legacy = db()->prepare(
            'SELECT COUNT(*)
             FROM report_deliveries
             WHERE log_day_id = :log_day_id
               AND delivery_type = "automatic"
               AND status = "sent"'
        );
        $legacy->execute(['log_day_id' => $logDayId]);

        return (int) $legacy->fetchColumn() > 0;
    }

    return false;
}

function carceris_report_attachment_for_format(array $logDay, array $entries, string $format): ?array
{
    return match ($format) {
        'none' => null,
        'plain_text' => [
            'filename' => carceris_report_download_filename($logDay, 'text'),
            'content_type' => 'text/plain; charset=UTF-8',
            'content' => carceris_render_log_report_plain_text($logDay, $entries),
        ],
        'html' => [
            'filename' => carceris_report_download_filename($logDay, 'html'),
            'content_type' => 'text/html; charset=UTF-8',
            'content' => carceris_render_log_report_html($logDay, $entries),
        ],
        'pdf' => [
            'filename' => carceris_report_download_filename($logDay, 'pdf'),
            'content_type' => 'application/pdf',
            'content' => carceris_render_log_report_pdf($logDay, $entries),
        ],
        default => throw new RuntimeException('Unsupported attachment format: ' . $format),
    };
}

function carceris_report_body_for_format(array $logDay, array $entries, string $format, string $attachmentFormat): array
{
    if ($format === 'plain_text') {
        return [
            'body_format' => 'plain_text',
            'body' => carceris_render_log_report_plain_text($logDay, $entries),
        ];
    }

    if ($format === 'html') {
        return [
            'body_format' => 'html',
            'body' => carceris_render_log_report_html($logDay, $entries),
        ];
    }

    if ($format === 'none') {
        if ($attachmentFormat === 'none') {
            throw new RuntimeException('Report body and attachment cannot both be set to None.');
        }

        return [
            'body_format' => 'plain_text',
            'body' => "The Carceris daily log report is attached.\n\nOperational Period: " . $logDay['log_label'] . "\n",
        ];
    }

    throw new RuntimeException('Unsupported report body format: ' . $format);
}

function carceris_record_report_send_delivery(
    array $logDay,
    array $settings,
    array $message,
    ?array $triggeredBy,
    string $deliveryType,
    string $status,
    ?string $errorMessage = null
): int {
    $stmt = db()->prepare(
        'INSERT INTO report_email_deliveries
            (log_day_id, delivery_type, transport, body_format, attachment_format, recipient_to, recipient_cc, recipient_bcc, subject, status, error_message, sent_at, triggered_by, created_at)
         VALUES
            (:log_day_id, :delivery_type, :transport, :body_format, :attachment_format, :recipient_to, :recipient_cc, :recipient_bcc, :subject, :status, :error_message, :sent_at, :triggered_by, NOW())'
    );

    $stmt->execute([
        'log_day_id' => (int) $logDay['id'],
        'delivery_type' => $deliveryType === 'automatic' ? 'automatic' : 'manual',
        'transport' => (string) ($settings['report_mail_transport'] ?? 'manual_only'),
        'body_format' => (string) ($settings['report_body_format'] ?? 'plain_text'),
        'attachment_format' => (string) ($settings['report_attachment_format'] ?? 'none'),
        'recipient_to' => implode(', ', $message['to'] ?? []),
        'recipient_cc' => implode(', ', $message['cc'] ?? []),
        'recipient_bcc' => implode(', ', $message['bcc'] ?? []),
        'subject' => (string) ($message['subject'] ?? carceris_report_subject($logDay)),
        'status' => in_array($status, ['pending', 'sent', 'failed', 'skipped'], true) ? $status : 'pending',
        'error_message' => $errorMessage,
        'sent_at' => $status === 'sent' ? current_datetime() : null,
        'triggered_by' => $triggeredBy ? (int) $triggeredBy['id'] : null,
    ]);

    return (int) db()->lastInsertId();
}

function carceris_send_log_day_report(array $logDay, ?array $triggeredBy, string $deliveryType): array
{
    $settings = carceris_mail_settings();
    $entries = get_entries_for_log_day((int) $logDay['id']);

    $bodyFormatSetting = (string) ($settings['report_body_format'] ?? 'plain_text');
    $attachmentFormat = (string) ($settings['report_attachment_format'] ?? 'none');

    $bodyData = carceris_report_body_for_format($logDay, $entries, $bodyFormatSetting, $attachmentFormat);
    $attachment = carceris_report_attachment_for_format($logDay, $entries, $attachmentFormat);

    $message = carceris_mail_message_from_settings(
        $settings,
        carceris_report_subject($logDay),
        $bodyData['body'],
        $bodyData['body_format']
    );

    if ($attachment !== null) {
        $message['attachments'][] = $attachment;
    }

    try {
        carceris_mail_send($settings, $message);

        $deliveryId = carceris_record_report_send_delivery(
            $logDay,
            $settings,
            $message,
            $triggeredBy,
            $deliveryType,
            'sent'
        );

        audit_event(
            $deliveryType === 'automatic' ? 'report_automatic_sent' : 'report_manual_sent',
            $triggeredBy ? (int) $triggeredBy['id'] : null,
            $triggeredBy['username'] ?? null,
            'Sent completed daily log. Operational date: ' . $logDay['operational_date'] . '. Transport: ' . ($settings['report_mail_transport'] ?? 'manual_only') . '.',
            'report_email_delivery',
            $deliveryId
        );

        return [
            'status' => 'sent',
            'delivery_id' => $deliveryId,
            'log_day_id' => (int) $logDay['id'],
            'operational_date' => $logDay['operational_date'],
        ];
    } catch (Throwable $exception) {
        $deliveryId = carceris_record_report_send_delivery(
            $logDay,
            $settings,
            $message,
            $triggeredBy,
            $deliveryType,
            'failed',
            $exception->getMessage()
        );

        audit_event(
            $deliveryType === 'automatic' ? 'report_automatic_failed' : 'report_manual_failed',
            $triggeredBy ? (int) $triggeredBy['id'] : null,
            $triggeredBy['username'] ?? null,
            'Daily log send failed. Operational date: ' . $logDay['operational_date'] . '. Error: ' . $exception->getMessage(),
            'report_email_delivery',
            $deliveryId
        );

        throw $exception;
    }
}

function carceris_send_previous_log_report_now(?array $triggeredBy, string $deliveryType = 'manual'): array
{
    $logDay = get_or_create_previous_log_day($triggeredBy ? (int) $triggeredBy['id'] : null);

    return carceris_send_log_day_report($logDay, $triggeredBy, $deliveryType);
}

function carceris_send_log_day_report_by_id(int $logDayId, ?array $triggeredBy, string $deliveryType = 'manual'): array
{
    $logDay = carceris_log_day_by_id($logDayId);

    if (!$logDay) {
        throw new RuntimeException('Daily log not found.');
    }

    return carceris_send_log_day_report($logDay, $triggeredBy, $deliveryType);
}


function carceris_scheduled_report_due(): array
{
    $settings = carceris_mail_settings();

    if (($settings['report_delivery_enabled'] ?? '0') !== '1') {
        return [
            'due' => false,
            'reason' => 'Automatic log delivery is disabled.',
        ];
    }

    $sendTime = carceris_validate_report_send_time((string) ($settings['report_send_time'] ?? '05:00'));
    $now = new DateTimeImmutable('now');
    $scheduledToday = new DateTimeImmutable($now->format('Y-m-d') . ' ' . $sendTime);

    if ($now < $scheduledToday) {
        return [
            'due' => false,
            'reason' => 'Scheduled send time has not arrived yet.',
        ];
    }

    $logDay = get_or_create_previous_log_day(null);

    if (carceris_report_delivery_already_sent((int) $logDay['id'])) {
        return [
            'due' => false,
            'reason' => 'The previous completed log has already been sent automatically.',
            'log_day' => $logDay,
        ];
    }

    return [
        'due' => true,
        'reason' => 'Scheduled report is due.',
        'log_day' => $logDay,
    ];
}

function carceris_run_scheduled_daily_report(): array
{
    $due = carceris_scheduled_report_due();

    if (!$due['due']) {
        audit_event(
            'report_automatic_skipped',
            null,
            null,
            $due['reason'],
            isset($due['log_day']) ? 'log_day' : null,
            isset($due['log_day']) ? (int) $due['log_day']['id'] : null
        );

        return [
            'status' => 'skipped',
            'reason' => $due['reason'],
            'log_day' => $due['log_day'] ?? null,
        ];
    }

    return carceris_send_log_day_report($due['log_day'], null, 'automatic');
}
